### ISSUE TITLE
[Proposed] AimeVideoPlayer Component 

### ISSUE THREAD

**Issue by bronz3beard** [aimementoring/blueprint#156] opened 2020-01-17 07:57 UTC
`AimeVideoPlayer` <- working title for component name.

We need to add this component to BP as we have a growing video asset collection for AIME which are used throughout the site.
It will be useful to standardize a video component that can handle any potential future changes to the video medium that may  be out of our control. e.g. `Vimeo` makes changes to....

These changes can be handled by [react-player](https://github.com/CookPete/react-player#usage) (this is out first best candidate for handling our BP video component)

The `AimeVideoPlayer`  needs to be a minimal design which can fit inline on any page where video medium is required.

*The initial plan is to add it directly to website-v5 to make sure we can have a `MVP POC`, once this is proven we will add the component to `blueprint`. 
This is the proposed approach as there are some doubts which may need to be addressed and it will speed up the process for problem solving them by adding directly to website, therefore getting it on to BP sooner.*

a potential alternative to `react-player` is `video.js` I believe this is currently being used, and has provided some challenges which `react-player` can relieve.

This issue is to add a fresh perspective on the video player and to also initiate the discussion around the component again. 
There may need to be some discussion around the `UX` expectation and potential limitation of the video component `e.g. how does it work on mobile devices, are we happy to prompt the user twice to press play` ? as we know with any interactive medium `UX` plays a key role, also considering no auto play with most browsers today.

**Additional context**
[Configure video player #31](https://github.com/aimementoring/blueprint/pull/31/commits)
[react-player props](https://github.com/CookPete/react-player#props)
[Trying to use the light mode of react-player #168](https://github.com/aimementoring/aime-portal/pull/168)
[react-player demo](https://cookpete.com/react-player/)
[Trying to use the light mode of react-player #168](https://github.com/aimementoring/aime-portal/pull/168/commits/d144545a184d7a6481264634a8d9d228c7cf7ec6)

**Comment by rin** [comment] 2020-01-17 13:24
A few screenshots from the Website Figmas (these might not be up to date, in doubt check here https://www.figma.com/file/cWlx1UwHaPZZW7i6RhInKI/Wf?node-id=8%3A32 )

<img width="345" alt="Screenshot 2020-01-17 at 20 20 43" src="https://user-images.githubusercontent.com/294558/72615380-2433a300-3967-11ea-8ac0-639b32dbf776.png">
<img width="447" alt="Screenshot 2020-01-17 at 20 21 05" src="https://user-images.githubusercontent.com/294558/72615381-2433a300-3967-11ea-8e68-ac48c1ef06c4.png">
<img width="398" alt="Screenshot 2020-01-17 at 20 21 44" src="https://user-images.githubusercontent.com/294558/72615382-24cc3980-3967-11ea-8c61-806a2a95bca0.png">

@charliemckenzie Happy for you to add any clarifications/explanations!

**Comment by charliemckenzie** [comment] 2020-01-22 11:03
Keen to chat about what we are able to do here :)
I kept it hella basic for now, but I can dive into it deeper with some more context. 

Here's anotherI designed for our proposed media manager :
https://www.figma.com/file/ESF77fLHZvTYGymRT5GeOFqk/AMP?node-id=35%3A569

Lemme know! :)

**Comment by mischacolley** [comment] 2020-01-22 22:14
This is sort of a duplicate of #24 right?

See my comment [here](https://github.com/aimementoring/blueprint/issues/24#issuecomment-478950277) for functionality we should support. The addition to add here would be integration with Contentful re reference from @bronz3beard. 

@charliemckenzie I don't reckon we need to chat about it ... can you just provide a design for the single stories page for the website as the one to work up here. I think that will be the simplest style we need to support and @rin / @bronz3beard can collaborate on brining it to life starting with basic features.

**Comment by charliemckenzie** [comment] 2020-01-28 15:12
I did a few here for the initial basic page... i think this will be re-usable for other pages. But i've got other ideas in mind for the future haha.

https://www.figma.com/file/cWlx1UwHaPZZW7i6RhInKI/Wf?node-id=92%3A434

if you scroll down you'll see some variations :) Let me know if it makes sense @bronz3beard @rin :)

**Comment by lulen11** [comment] 2020-03-17 03:50
hey @bronz3beard, could we close this one because it's covered in #24 ?

**Comment by bronz3beard** [comment] 2020-03-17 11:15
#24 is an old component, which have similarities in the information needed for development I didn't want to remove 24 as if has video requirements, but recently you added a check list which i ticked off, so maybe they are the new requirements?

I have just developed the video comp to follow some of the things mentioned and some of the things in 24, I think you might be more across what is required for the video component so feel free to remove what you need to for clarity. 

I think anything that needs to be changed moving forward will not come from what we have done 😃

**Comment by mischacolley** [comment] 2020-03-30 03:39
@rin @lulen11 can we close this?

**Comment by rin** [comment] 2020-03-30 07:51
I think we can! Please reopen if I missed something!

**Closed by rin** 2020-03-30 07:51 UTC
Labels: component-proposed, content:video, project:blueprint
